### ISSUE TITLE
fatal error: H5Cpp.h: No such file or directory

### ISSUE THREAD

**Issue by puren** [felja633/kinectv2_decoders#1]
Hello,

I use Ubuntu 16.04.
When I run make in build directory, I get the following error:
`fatal error: H5Cpp.h: No such file or directory`
cmake can find HDF5 libraries:
`-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.8.16") `

So, I cannot figure out why it cannot detect include file.
I appreciate any help.

**Comment by felja633** [comment]
Hi,

I had forgotten to add the HL component in the find_package command for HDF5. I have pushed a fix so please try the new version. 

Thank you for detecting this!
